---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: uma-deployment
spec:
 replicas: 2
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: uma
 template:
  metadata:
   name: uma
   labels:
     app: uma 
  spec: 
    containers:
    - name: uma
      image: umagoudkola/kotiu:v1
      imagePullPolicy: Always
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: uma-service
spec:
  type: NodePort
  selector:
   app: uma
  ports:
   - port: 80
     targetPort: 80
...
